/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  // reset próprio já vive em globals.css — evita conflito com as páginas antigas
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'on-primary': '#003737',
        'on-tertiary-container': '#0063c3',
        surface: '#121314',
        'surface-dim': '#121314',
        'secondary-container': '#454749',
        'secondary-fixed': '#e2e2e5',
        'inverse-on-surface': '#303031',
        'inverse-surface': '#e3e2e3',
        'primary-fixed': '#00fbfb',
        secondary: '#c6c6c9',
        'secondary-fixed-dim': '#c6c6c9',
        'on-surface': '#e3e2e3',
        'on-secondary-container': '#b4b5b7',
        'on-tertiary-fixed': '#001b3e',
        'on-secondary': '#2f3133',
        'tertiary-fixed-dim': '#aac7ff',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#d6e3ff',
        'on-primary-container': '#007070',
        'surface-container-high': '#292a2b',
        'on-tertiary-fixed-variant': '#00468d',
        'surface-container-lowest': '#0d0e0f',
        'on-secondary-fixed-variant': '#454749',
        'surface-tint': '#00dddd',
        tertiary: '#ffffff',
        background: '#121314',
        primary: '#ffffff',
        'surface-container-highest': '#343536',
        'on-background': '#e3e2e3',
        'outline-variant': '#3a4a49',
        error: '#ffb4ab',
        'tertiary-fixed': '#d6e3ff',
        'on-primary-fixed': '#002020',
        'surface-variant': '#343536',
        'on-secondary-fixed': '#1a1c1e',
        'primary-container': '#00fbfb',
        'on-tertiary': '#003064',
        'surface-container': '#1f2021',
        'on-primary-fixed-variant': '#004f4f',
        'inverse-primary': '#006a6a',
        'primary-fixed-dim': '#00dddd',
        'on-error': '#690005',
        'on-surface-variant': '#b9cac9',
        'surface-bright': '#39393a',
        outline: '#839493',
        'surface-container-low': '#1b1c1d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'grid-unit': '8px',
        'container-max-width': '1280px',
        'margin-desktop': '64px',
        gutter: '24px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontFamily: {
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
